namespace CurrencyExchangeApi.Models.ResponseModels
{
    public class GetLatestCurrenciesResponse
    {

        public Rates Rates { get; set; }
    }

    public class Rates
    {
        public int? AED { get; set; }
        public int? AFN { get; set; }
        public int? ALL { get; set; }
        public int? AMD { get; set; }
        public int? ANG { get; set; }
        public int? AOA { get; set; }
        public int? ARS { get; set; }
        public int? AUD { get; set; }
        public int? AWG { get; set; }
        public int? AZN { get; set; }
        public int? BAM { get; set; }
        public int? BBD { get; set; }
        public int? BDT { get; set; }
        public int? BGN { get; set; }
        public int? BHD { get; set; }
        public int? BIF { get; set; }
        public int? BMD { get; set; }
        public int? BND { get; set; }
        public int? BOB { get; set; }
        public int? BRL { get; set; }
        public int? BSD { get; set; }
        public int? BTC { get; set; }
        public int? BTN { get; set; }
        public int? BWP { get; set; }
        public int? BYN { get; set; }
        public int? BYR { get; set; }
        public int? BZD { get; set; }
        public int? CAD { get; set; }
        public int? CDF { get; set; }
        public int? CHF { get; set; }
        public int? CLF { get; set; }
        public int? CLP { get; set; }
        public int? CNY { get; set; }
        public int? COP { get; set; }
        public int? CRC { get; set; }
        public int? CUC { get; set; }
        public int? CUP { get; set; }
        public int? CVE { get; set; }
        public int? CZK { get; set; }
        public int? DJF { get; set; }
        public int? DKK { get; set; }
        public int? DOP { get; set; }
        public int? DZD { get; set; }
        public int? EGP { get; set; }
        public int? ERN { get; set; }
        public int? ETB { get; set; }
        public int? EUR { get; set; }
        public int? FJD { get; set; }
        public int? FKP { get; set; }
        public int? GBP { get; set; }
        public int? GEL { get; set; }
        public int? GGP { get; set; }
        public int? GHS { get; set; }
        public int? GIP { get; set; }
        public int? GMD { get; set; }
        public int? GNF { get; set; }
        public int? GTQ { get; set; }
        public int? GYD { get; set; }
        public int? HKD { get; set; }
        public int? HNL { get; set; }
        public int? HRK { get; set; }
        public int? HTG { get; set; }
        public int? HUF { get; set; }
        public int? IDR { get; set; }
        public int? ILS { get; set; }
        public int? IMP { get; set; }
        public int? INR { get; set; }
        public int? IQD { get; set; }
        public int? IRR { get; set; }
        public int? ISK { get; set; }
        public int? JEP { get; set; }
        public int? JMD { get; set; }
        public int? JOD { get; set; }
        public int? JPY { get; set; }
        public int? KES { get; set; }
        public int? KGS { get; set; }
        public int? KHR { get; set; }
        public int? KMF { get; set; }
        public int? KPW { get; set; }
        public int? KRW { get; set; }
        public int? KWD { get; set; }
        public int? KYD { get; set; }
        public int? KZT { get; set; }
        public int? LAK { get; set; }
        public int? LBP { get; set; }
        public int? LKR { get; set; }
        public int? LRD { get; set; }
        public int? LSL { get; set; }
        public int? LTL { get; set; }
        public int? LVL { get; set; }
        public int? LYD { get; set; }
        public int? MAD { get; set; }
        public int? MDL { get; set; }
        public int? MGA { get; set; }
        public int? MKD { get; set; }
        public int? MMK { get; set; }
        public int? MNT { get; set; }
        public int? MOP { get; set; }
        public int? MRO { get; set; }
        public int? MUR { get; set; }
        public int? MVR { get; set; }
        public int? MWK { get; set; }
        public int? MXN { get; set; }
        public int? MYR { get; set; }
        public int? MZN { get; set; }
        public int? NAD { get; set; }
        public int? NGN { get; set; }
        public int? NIO { get; set; }
        public int? NOK { get; set; }
        public int? NPR { get; set; }
        public int? NZD { get; set; }
        public int? OMR { get; set; }
        public int? PAB { get; set; }
        public int? PEN { get; set; }
        public int? PGK { get; set; }
        public int? PHP { get; set; }
        public int? PKR { get; set; }
        public int? PLN { get; set; }
        public int? PYG { get; set; }
        public int? QAR { get; set; }
        public int? RON { get; set; }
        public int? RSD { get; set; }
        public int? RUB { get; set; }
        public int? RWF { get; set; }
        public int? SAR { get; set; }
        public int? SBD { get; set; }
        public int? SCR { get; set; }
        public int? SDG { get; set; }
        public int? SEK { get; set; }
        public int? SGD { get; set; }
        public int? SHP { get; set; }
        public int? SLL { get; set; }
        public int? SOS { get; set; }
        public int? SRD { get; set; }
        public int? STD { get; set; }
        public int? SVC { get; set; }
        public int? SYP { get; set; }
        public int? SZL { get; set; }
        public int? THB { get; set; }
        public int? TJS { get; set; }
        public int? TMT { get; set; }
        public int? TND { get; set; }
        public int? TOP { get; set; }
        public int? TRY { get; set; }
        public int? TTD { get; set; }
        public int? TWD { get; set; }
        public int? TZS { get; set; }
        public int? UAH { get; set; }
        public int? UGX { get; set; }
        public int? USD { get; set; }
        public int? UYU { get; set; }
        public int? UZS { get; set; }
        public int? VND { get; set; }
        public int? VUV { get; set; }
        public int? WST { get; set; }
        public int? XAF { get; set; }
        public int? XAG { get; set; }
        public int? XAU { get; set; }
        public int? XCD { get; set; }
        public int? XDR { get; set; }
        public int? XOF { get; set; }
        public int? XPF { get; set; }
        public int? YER { get; set; }
        public int? ZAR { get; set; }
        public int? ZMK { get; set; }
        public int? ZMW { get; set; }
        public int? ZWL { get; set; }
    }
}

